"""URL routes for the MFA app
Grouped by features: auth, verifications, setup, user security, admin MFA,
and password reset wrappers.
"""
from django.urls import path, reverse_lazy
from django.conf import settings
from . import views
from . import ajax_views
from .views_real_admin import (
    admin_session_management, admin_geolocation_tracking, admin_threat_intelligence,
    admin_user_behavior_analytics, admin_device_fingerprinting, admin_incident_response,
    admin_notification_center, admin_api_management,
    admin_enterprise_reporting,
    admin_forensics_audit, admin_roles_management
)
from .views_advanced import (
    admin_risk_assessment,
    admin_device_analytics,
    admin_workflow_automation,
    admin_predictive_analytics,
)
from .ajax_views import (
    admin_save_ml_config,
    admin_mark_all_read,
    admin_export_risk_report,
    admin_block_device,
    admin_export_audit_logs,
    admin_start_log_correlation,
    admin_run_timeline_analysis,
    admin_run_pattern_detection,
    admin_run_risk_assessment,
    admin_geo_map,
    admin_terminate_sessions,
    admin_export_sessions,
    admin_save_security_settings,
    admin_export_location_data,
    admin_restrict_user,
    admin_export_model_metrics,
    admin_export_threat_report,
    admin_block_threat,
    admin_export_policy_logs,
    admin_export_organizations,
    admin_export_permissions,
    admin_mark_notification_read,
    admin_delete_notification,
    admin_save_notification_settings,
    admin_create_geo_rule,
    admin_suspicious_locations,
    admin_travel_alerts,
    admin_export_geo_report,
    admin_run_backup,
    admin_backup_settings,
    admin_restore_backup
)
from .ajax_views_realtime import (
    live_activity_feed,
    live_system_stats,
    live_session_data,
    live_threat_data
)
from .forms import CustomPasswordResetForm
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from .views import CustomPasswordResetDoneView
from .views_admin_api import (
    api_device_types,
    api_risk_distribution,
    api_logs_summary,
    api_incidents_summary,
    api_incidents_active,
    api_incident_categories,
    api_incident_timeline,
    api_forensics_summary,
    api_compliance_status,
    api_ml_summary,
    api_audit_event_detail,
    api_user_security_score,
    api_users_security_scores,
    api_incident_update,
)
app_name = 'mfa'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('login/backup-code/', views.backup_code_login_view, name='backup_code_login'),
    path('profile/', views.profile_view, name='profile'),
    path('my-cases/', views.my_cases_view, name='my_cases'),
    path('open-case/', views.open_case_view, name='open_case'),
    path('verify/totp/', views.verify_totp_view, name='verify_totp'),
    path('verify/email/', views.verify_email_view, name='verify_email'),
    path('verify/signup-email/', views.verify_email_signup_view, name='verify_email_signup'),
    path('verify/sms/', views.verify_sms_view, name='verify_sms'),
    path('choose/', views.choose_method_view, name='choose_method'),
    path('passkey/auth-begin/', views.passkey_auth_begin, name='passkey_auth_begin'),
    path('passkey/auth-complete/', views.passkey_auth_complete, name='passkey_auth_complete'),
    path('setup/totp/', views.setup_totp_view, name='setup_totp'),
    path('setup/passkey/', views.setup_passkey_view, name='setup_passkey'),
    path('check-sms-login/', views.check_sms_login_view, name='check_sms_login'),
    path('setup/sms/', views.setup_sms_view, name='setup_sms'),
    path('verify-sms-setup/', views.verify_sms_setup_view, name='verify_sms_setup'),
    path('backup-codes/', views.backup_codes_view, name='backup_codes'),
    path('security-hub/', views.security_hub_view, name='security_hub'),
    path('disable_totp/', views.disable_totp_view, name='disable_totp'),
    path('disable_sms/', views.disable_sms_view, name='disable_sms'),
    path('disable_passkeys/', views.disable_passkeys_view, name='disable_passkeys'),
    path('reauth/', views.reauth_view, name='reauth'),
    path('admin/login/', views.admin_login_view, name='admin_login'),
    path('admin/verify/email/', views.admin_verify_email_view, name='admin_verify_email'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/statistics/', views.admin_statistics, name='admin_statistics'),
    path('admin/realtime-monitoring/', views.admin_realtime_monitoring, name='admin_realtime_monitoring'),
    # Admin Logs
    path('admin/logs/', views.admin_logs_list, name='admin_logs'),
    # Removed roles UI routes
    path('admin/settings/', views.admin_settings_view, name='admin_settings'),
    path('admin/report-settings/', views.admin_report_settings_view, name='admin_report_settings'),
    # Admin Users management
    path('admin/users/', views.admin_users_list, name='admin_users'),
    path('admin/users/bulk/', views.admin_users_bulk_action, name='admin_users_bulk'),
    path('admin/users/export/', views.admin_users_export, name='admin_users_export'),
    path('admin/users/<int:user_id>/', views.admin_user_detail, name='admin_user_detail'),
    path('admin/users/<int:user_id>/activate/', views.admin_activate_user, name='admin_activate_user'),
    path('admin/users/<int:user_id>/deactivate/', views.admin_deactivate_user, name='admin_deactivate_user'),
    path('admin/users/<int:user_id>/reset-mfa/', views.admin_reset_mfa, name='admin_reset_mfa'),
    path('admin/users/<int:user_id>/send-reset/', views.admin_send_password_reset, name='admin_send_password_reset'),
    path('admin/users/<int:user_id>/delete/', views.admin_delete_user, name='admin_delete_user'),
    path('admin/contact-user/', views.admin_contact_user, name='admin_contact_user'),
    path('admin/restrict-user/', views.admin_restrict_user, name='admin_restrict_user'),
    path('admin/logout-beacon/', views.admin_logout_beacon_view, name='admin_logout_beacon'),
    # Advanced Admin Dashboards
    path('admin/risk-assessment/', admin_risk_assessment, name='admin_risk_assessment'),
    path('admin/device-analytics/', admin_device_analytics, name='admin_device_analytics'),
    # Consolidated: route compliance-report to enterprise_reporting (single reporting center)
    path('admin/compliance-report/', admin_enterprise_reporting, name='admin_compliance_report'),
    path('admin/workflow-automation/', admin_workflow_automation, name='admin_workflow_automation'),
    path('admin/predictive-analytics/', admin_predictive_analytics, name='admin_predictive_analytics'),
    # Enterprise Security URLs
    path('admin/session-management/', admin_session_management, name='admin_session_management'),
    path('admin/geolocation-tracking/', admin_geolocation_tracking, name='admin_geolocation_tracking'),
    path('admin/threat-intelligence/', admin_threat_intelligence, name='admin_threat_intelligence'),
    path('admin/api-management/', admin_api_management, name='admin_api_management'),
    path('admin/enterprise-reporting/', admin_enterprise_reporting, name='admin_enterprise_reporting'),
    path('admin/user-behavior-analytics/', admin_user_behavior_analytics, name='admin_user_behavior_analytics'),
    # Advanced Features URLs
    path('admin/device-fingerprinting/', admin_device_fingerprinting, name='admin_device_fingerprinting'),
    path('admin/notification-center/', admin_notification_center, name='admin_notification_center'),
    path('admin/incident-response/', admin_incident_response, name='admin_incident_response'),
    # Consolidated: ML Risk Engine under Predictive Analytics
    path('admin/ml-risk-engine/', admin_predictive_analytics, name='admin_ml_risk_engine'),
    path('admin/forensics-audit/', admin_forensics_audit, name='admin_forensics_audit'),
    path('admin/roles/', admin_roles_management, name='admin_roles_management'),
    # AJAX endpoints
    path('admin/ajax/save-ml-config/', admin_save_ml_config, name='admin_save_ml_config'),
    path('admin/ajax/mark-all-read/', admin_mark_all_read, name='admin_mark_all_read'),
    path('admin/ajax/export-risk-report/', admin_export_risk_report, name='admin_export_risk_report'),
    path('admin/ajax/export-audit-logs/', admin_export_audit_logs, name='admin_export_audit_logs'),
    path('admin/ajax/start-log-correlation/', admin_start_log_correlation, name='admin_start_log_correlation'),
    path('admin/ajax/run-timeline-analysis/', admin_run_timeline_analysis, name='admin_run_timeline_analysis'),
    path('admin/ajax/run-pattern-detection/', admin_run_pattern_detection, name='admin_run_pattern_detection'),
    path('admin/ajax/run-risk-assessment/', admin_run_risk_assessment, name='admin_run_risk_assessment'),
    path('admin/ajax/block-device/', admin_block_device, name='admin_block_device'),
    path('admin/ajax/geo-map/', admin_geo_map, name='admin_geo_map'),
    path('admin/ajax/terminate-sessions/', admin_terminate_sessions, name='admin_terminate_sessions'),
    path('admin/ajax/export-sessions/', admin_export_sessions, name='admin_export_sessions'),
    path('admin/ajax/save-security-settings/', admin_save_security_settings, name='admin_save_security_settings'),
    path('admin/ajax/export-location-data/', admin_export_location_data, name='admin_export_location_data'),
    path('admin/ajax/restrict-user/', admin_restrict_user, name='admin_restrict_user'),
    path('admin/ajax/export-model-metrics/', admin_export_model_metrics, name='admin_export_model_metrics'),
    path('admin/ajax/export-threat-report/', admin_export_threat_report, name='admin_export_threat_report'),
    path('admin/ajax/block-threat/', admin_block_threat, name='admin_block_threat'),
    path('admin/ajax/export-policy-logs/', admin_export_policy_logs, name='admin_export_policy_logs'),
    path('admin/ajax/export-organizations/', admin_export_organizations, name='admin_export_organizations'),
    path('admin/ajax/export-permissions/', admin_export_permissions, name='admin_export_permissions'),
    path('admin/ajax/mark-notification-read/', admin_mark_notification_read, name='admin_mark_notification_read'),
    path('admin/ajax/delete-notification/', admin_delete_notification, name='admin_delete_notification'),
    path('admin/ajax/save-notification-settings/', admin_save_notification_settings, name='admin_save_notification_settings'),
    path('admin/ajax/create-geo-rule/', admin_create_geo_rule, name='admin_create_geo_rule'),
    path('admin/ajax/suspicious-locations/', admin_suspicious_locations, name='admin_suspicious_locations'),
    path('admin/ajax/travel-alerts/', admin_travel_alerts, name='admin_travel_alerts'),
    path('admin/ajax/export-geo-report/', admin_export_geo_report, name='admin_export_geo_report'),
    path('admin/ajax/run-backup/', admin_run_backup, name='admin_run_backup'),
    path('admin/ajax/backup-settings/', admin_backup_settings, name='admin_backup_settings'),
    path('admin/ajax/restore-backup/', admin_restore_backup, name='admin_restore_backup'),
    # Roles AJAX
    path('admin/ajax/roles/create/', ajax_views.admin_roles_create, name='admin_roles_create'),
    path('admin/ajax/roles/delete/', ajax_views.admin_roles_delete, name='admin_roles_delete'),
    path('admin/ajax/roles/update-perms/', ajax_views.admin_roles_update_perms, name='admin_roles_update_perms'),
    path('admin/ajax/roles/list/', ajax_views.admin_roles_list, name='admin_roles_list'),
    path('admin/ajax/roles/assign-user/', ajax_views.admin_assign_role_to_user, name='admin_assign_role_to_user'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='auth/password_reset_form.html',
        email_template_name='auth/password_reset_email.txt',
        html_email_template_name='auth/password_reset_email.html',
        subject_template_name='auth/password_reset_subject.txt',
        success_url=reverse_lazy('mfa:password_reset_done'),
        form_class=CustomPasswordResetForm,
        extra_email_context={
            'brand_color': settings.BRAND_COLOR,
            'brand_color_hover': settings.BRAND_COLOR_HOVER,
            'brand_color_weak': settings.BRAND_COLOR_WEAK,
        }
    ),
        name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(
        template_name='auth/password_reset_confirm.html',
        success_url=reverse_lazy('mfa:password_reset_complete')),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='auth/password_reset_complete.html'),
        name='password_reset_complete'),
    # Real-time monitoring AJAX endpoints
    path('admin/ajax/live-activity-feed/', live_activity_feed, name='live_activity_feed'),
    path('admin/ajax/live-system-stats/', live_system_stats, name='live_system_stats'),
    path('admin/ajax/live-session-data/', live_session_data, name='live_session_data'),
    path('admin/ajax/live-threat-data/', live_threat_data, name='live_threat_data'),
    # Admin Analytics API (real data)
    path('admin/api/device-types/', api_device_types, name='admin_api_device_types'),
    path('admin/api/risk-distribution/', api_risk_distribution, name='admin_api_risk_distribution'),
    path('admin/api/logs-summary/', api_logs_summary, name='admin_api_logs_summary'),
    path('admin/api/incidents/summary/', api_incidents_summary, name='admin_api_incidents_summary'),
    path('admin/api/incidents/active/', api_incidents_active, name='admin_api_incidents_active'),
    path('admin/api/incidents/categories/', api_incident_categories, name='admin_api_incident_categories'),
    path('admin/api/incidents/timeline/', api_incident_timeline, name='admin_api_incident_timeline'),
    path('admin/api/incidents/update/', api_incident_update, name='admin_api_incident_update'),
    path('admin/api/forensics/summary/', api_forensics_summary, name='admin_api_forensics_summary'),
    path('admin/api/compliance/status/', api_compliance_status, name='admin_api_compliance_status'),
    path('admin/api/ml/summary/', api_ml_summary, name='admin_api_ml_summary'),
    path('admin/api/audit/event/', api_audit_event_detail, name='admin_api_audit_event_detail'),
    path('admin/api/users/<int:user_id>/security-score/', api_user_security_score, name='admin_api_user_security_score'),
    path('admin/api/users/security-scores/', api_users_security_scores, name='admin_api_users_security_scores'),
]
