# Generated by Django 5.2.5 on 2025-08-25 20:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa', '0015_mfasettings_report_csv_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('threat_type', models.CharField(choices=[('malware', 'Malware'), ('phishing', 'Phishing'), ('spam', 'Spam'), ('botnet', 'Botnet'), ('scanner', 'Scanner'), ('bruteforce', 'Brute Force')], max_length=20)),
                ('threat_score', models.IntegerField(default=0)),
                ('source', models.CharField(max_length=100)),
                ('last_seen', models.DateTimeField()),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address'], name='mfa_threati_ip_addr_eb4394_idx'), models.Index(fields=['threat_score'], name='mfa_threati_threat__32fa32_idx'), models.Index(fields=['is_blocked'], name='mfa_threati_is_bloc_a71e36_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField()),
                ('request_size', models.IntegerField(default=0)),
                ('response_size', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['endpoint', 'timestamp'], name='mfa_apiusag_endpoin_b41577_idx'), models.Index(fields=['user', 'timestamp'], name='mfa_apiusag_user_id_7d87ad_idx'), models.Index(fields=['status_code'], name='mfa_apiusag_status__239c19_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('gdpr', 'GDPR Compliance'), ('hipaa', 'HIPAA Compliance'), ('sox', 'SOX Compliance'), ('pci_dss', 'PCI DSS Compliance'), ('iso27001', 'ISO 27001 Compliance')], max_length=20)),
                ('report_period_start', models.DateTimeField()),
                ('report_period_end', models.DateTimeField()),
                ('compliance_score', models.FloatField()),
                ('findings', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['report_type', 'generated_at'], name='mfa_complia_report__bb92ae_idx'), models.Index(fields=['compliance_score'], name='mfa_complia_complia_ba9c85_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(max_length=64, unique=True)),
                ('device_info', models.JSONField()),
                ('is_trusted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('fraud_score', models.IntegerField(default=0)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_fingerprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='mfa_devicef_user_id_61ea44_idx'), models.Index(fields=['fingerprint_hash'], name='mfa_devicef_fingerp_290d02_idx'), models.Index(fields=['is_trusted'], name='mfa_devicef_is_trus_cf7327_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=20, unique=True)),
                ('incident_type', models.CharField(choices=[('suspicious_login', 'Suspicious Login'), ('brute_force', 'Brute Force Attack'), ('anomaly_detected', 'Anomaly Detected'), ('threat_detected', 'Threat Detected'), ('device_fraud', 'Device Fraud'), ('location_anomaly', 'Location Anomaly')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'severity'], name='mfa_securit_status_ed4388_idx'), models.Index(fields=['incident_type'], name='mfa_securit_inciden_0a41c4_idx'), models.Index(fields=['created_at'], name='mfa_securit_created_20a29c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('security_alert', 'Security Alert'), ('system_notification', 'System Notification'), ('incident_update', 'Incident Update'), ('compliance_alert', 'Compliance Alert')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('action_required', models.BooleanField(default=False)),
                ('action_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_read'], name='mfa_securit_user_id_47d818_idx'), models.Index(fields=['priority'], name='mfa_securit_priorit_e7f50a_idx'), models.Index(fields=['created_at'], name='mfa_securit_created_8e5414_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('location_country', models.CharField(blank=True, max_length=2)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('device_fingerprint', models.CharField(blank=True, max_length=64)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('anomaly_reasons', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'timestamp'], name='mfa_userbeh_user_id_46a643_idx'), models.Index(fields=['is_anomaly'], name='mfa_userbeh_is_anom_85983d_idx'), models.Index(fields=['action'], name='mfa_userbeh_action_bdd5ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_fingerprint', models.CharField(blank=True, max_length=64)),
                ('location_country', models.CharField(blank=True, max_length=2)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='mfa_userses_user_id_2b4b08_idx'), models.Index(fields=['ip_address'], name='mfa_userses_ip_addr_f249c1_idx'), models.Index(fields=['is_suspicious'], name='mfa_userses_is_susp_a31741_idx')],
            },
        ),
    ]
